name: Build Android APK and upload to Play Store

on:
  push:
    tags:
      - beta-*

jobs:
  beta-android:
    name: Build Android APK and upload to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1
        with:
          persist-credentials: false
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.5'
          bundler-cache: true
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '16.x'
      - name: Install yarn dependencies
        run: yarn install
      - name: Restore gems cache or create a new cache entry
        uses: actions/cache@v2
        with:
          path: android/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('android/**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          chmod a+x ./gradlew
        working-directory: android
      - name: Build APK
        run: ./gradlew clean assembleDebug
        working-directory: ./android
