name: Build Android APK and upload to Play Store

on:
  push:
    branches:
      - main
    tags:
      - beta-*

jobs:
  beta-android:
    name: Build Android APK and upload to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1
        with:
          persist-credentials: false

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build APK
        run: ./gradlew clean assembleRelease --no-daemon
        working-directory: android
