name: Build Android APK and upload to Play Store

on:
  push:
    tags:
      - beta-*

jobs:
  beta-android:
    name: Build Android APK and upload to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1
        with:
          persist-credentials: false

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install dependencies
        run: npm install

      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          chmod a+x ./gradlew
        working-directory: android

      - name: Build APK
        run: ./gradlew clean assembleRelease --no-daemon
        working-directory: android
