name: NEPAL Build

on:
  push:
    tags:
      - v-*

jobs:
  beta-android:
    name: Build Android APK and upload to Play Store
    runs-on: ubuntu-latest
    env:
      API_URL: https://coachdigital.org/np/api
      COUNTRY: np
      LOGIN_MODE: OTP

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v1
        with:
          persist-credentials: false

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Add chmod
        run: chmod +x ./scripts/switch-to-nepal.sh

      - name: Switch to Nepal's config
        run: ./scripts/switch-to-nepal.sh

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build APK
        run: ./gradlew clean assembleRelease --no-daemon
        working-directory: android

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: android/app/build/outputs/apk/release/app-release.apk
